# Generated by Django 3.0.6 on 2020-05-15 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('mobile', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('jar_rate', models.IntegerField()),
                ('supply_begin', models.DateField(blank=True, max_length=255, null=True, verbose_name='Date format: year-month-date')),
                ('tk_previous_due', models.IntegerField(blank=True, default=0, null=True)),
                ('jar_previous_due', models.IntegerField(blank=True, default=0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('mobile', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('salary', models.IntegerField()),
                ('duty_Area', models.CharField(max_length=255, null=True)),
                ('job_Started', models.DateField(blank=True, null=True, verbose_name='Date format: year-month-day')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jar_given', models.IntegerField(blank=True, default=0, null=True)),
                ('jar_collect', models.IntegerField(blank=True, default=0, null=True)),
                ('tk_collect', models.IntegerField(blank=True, default=0, null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('customer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pura.Customer')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pura.Staff'),
        ),
    ]
