# Generated by Django 3.0.6 on 2020-05-19 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pura', '0002_cost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cost',
        ),
    ]
