# Generated by Django 3.0.6 on 2020-05-19 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pura', '0003_delete_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('cost_id', models.AutoField(primary_key=True, serialize=False)),
                ('cost_details', models.CharField(max_length=255)),
                ('cost_amount', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
