# Generated by Django 3.0.6 on 2020-06-05 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pura', '0005_auto_20200604_0132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
    ]
