# Generated by Django 3.0.6 on 2020-06-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pura', '0006_auto_20200606_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_id',
            field=models.IntegerField(),
        ),
    ]
