# Generated by Django 3.0.6 on 2020-06-07 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pura', '0009_auto_20200607_2349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
    ]
